version: '3.8'

services:
  # Infrastructure Services
  zookeeper:
    extends:
      file: docker-compose.yml
      service: zookeeper

  kafka:
    extends:
      file: docker-compose.yml
      service: kafka

  mongodb:
    extends:
      file: docker-compose.yml
      service: mongodb

  redis:
    extends:
      file: docker-compose.yml
      service: redis

  # Application Services
  api-gateway:
    build:
      context: ./backend/api-gateway
      dockerfile: Dockerfile.prod
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - KAFKA_BROKERS=kafka:29092
      - MONGODB_URI=mongodb://mongodb:27017/order-management
      - REDIS_URL=redis://redis:6379
    depends_on:
      kafka:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy

  order-service:
    build:
      context: ./backend/order-service
      dockerfile: Dockerfile.prod
    environment:
      - NODE_ENV=production
      - PORT=3001
      - KAFKA_BROKERS=kafka:29092
      - MONGODB_URI=mongodb://mongodb:27017/order-management
    depends_on:
      kafka:
        condition: service_healthy
      mongodb:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://localhost:4000
    depends_on:
      - api-gateway

volumes:
  mongodb_data: 